### PR TITLE
Silex structure

### PR DESCRIPTION
**Pull request by rpalladino**
I made some changes to give the Silex app more structure:

- Added an extended Application class to handle most of the application bootstrapping.
- Made controller classes into services, which allows constructor injection of dependencies.
- Added a view listener that will render any array returned from a controller using a Twig template (which gets specified as a request attribute when the controller is mapped to a route).
- Moved route-to-controller mapping to a controller provider.
- Added a service provider for the Meetup service.

### CODE REVIEW

**Comment by SammyK** [comment]
Love it! :)

**Comment by stevenmaguire** [comment]
Is this ready to merge?

**Comment by rpalladino** [comment]
I think both this and #6 are ready to go.

**Comment by stevenmaguire** [comment]
@nickescobedo or @SammyK could make that happen for us!

**Comment by SammyK** [comment]
Double ping @nickescobedo :)

**Comment by nickescobedo** [comment]
Whoops looks like I merged #6 before #5... Says there are conflicts now. @rpalladino

**Comment by SammyK** [comment]
Let me know if you guys need help resolving the conflicts with this. I still haven't pulled in the changes yet but I should have some time next week to look at them and add my 2 cents. :)

**Comment by rpalladino** [comment]
@nickescobedo, no problem. When you merged #6, you merged all these commits as well since it was based off the same branch as this PR. I'll go ahead and close this.

**Comment by SammyK** [comment]
@rpalladino Do you need to send any more PR's or is the master branch up-to-date with your changes?

**Comment by rpalladino** [comment]
It's up to date.

**Comment by SammyK** [comment]
Yay! :)

**Pull request closed without merging**
